#include "hostapd.hpp"

#include <cstdlib>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <array>

namespace fs = std::filesystem;

namespace apm::linux_backend {

namespace {

int read_pid(const std::string& pid_file) {
    std::ifstream in(pid_file);
    if (!in.is_open()) return -1;
    int pid = -1;
    in >> pid;
    return pid;
}

bool command_exists(const std::string& cmd) {
    std::string check = "which " + cmd + " >/dev/null 2>&1";
    return std::system(check.c_str()) == 0;
}

std::string run_cmd_output(const std::string& cmd) {
    std::string result;
    std::array<char, 256> buffer;
    FILE* pipe = popen(cmd.c_str(), "r");
    if (!pipe) return "";
    while (fgets(buffer.data(), buffer.size(), pipe) != nullptr) {
        result += buffer.data();
    }
    pclose(pipe);
    return result;
}

} // namespace

HostapdManager::~HostapdManager() {
    stop();
}

std::string HostapdManager::generate_config_string(const AccessPointConfig& config) {
    std::ostringstream oss;
    oss << "# hostapd.conf generated by AP-Generator\n";
    oss << "interface=" << config.interface << "\n";
    oss << "driver=nl80211\n";
    oss << "ssid=" << config.ssid << "\n";

    if (config.channel >= 36) {
        oss << "hw_mode=a\n";
        oss << "ieee80211ac=1\n";
    } else {
        oss << "hw_mode=g\n";
    }

    oss << "channel=" << config.channel << "\n";
    oss << "ieee80211n=1\n";
    oss << "wmm_enabled=1\n";

    if (!config.bssid.empty()) {
        oss << "bssid=" << config.bssid << "\n";
    }

    switch (config.security) {
        case SecurityMode::Open:
            oss << "auth_algs=1\n";
            oss << "wpa=0\n";
            break;
        case SecurityMode::WPA2:
            oss << "auth_algs=1\n";
            oss << "wpa=2\n";
            oss << "wpa_key_mgmt=WPA-PSK\n";
            oss << "rsn_pairwise=CCMP\n";
            oss << "wpa_passphrase=" << config.password << "\n";
            break;
        case SecurityMode::WPA3:
            oss << "auth_algs=1\n";
            oss << "wpa=2\n";
            oss << "wpa_key_mgmt=SAE\n";
            oss << "rsn_pairwise=CCMP\n";
            oss << "sae_password=" << config.password << "\n";
            oss << "ieee80211w=2\n";
            break;
        case SecurityMode::WPA2WPA3:
            oss << "auth_algs=1\n";
            oss << "wpa=2\n";
            oss << "wpa_key_mgmt=WPA-PSK SAE\n";
            oss << "rsn_pairwise=CCMP\n";
            oss << "wpa_passphrase=" << config.password << "\n";
            oss << "sae_password=" << config.password << "\n";
            oss << "ieee80211w=1\n";
            break;
    }

    return oss.str();
}

bool HostapdManager::start(const AccessPointConfig& config, std::string* error_msg) {
    std::error_code ec;
    fs::create_directories("config/run", ec);

    // Save hostapd.conf
    std::ofstream out(config_path_);
    if (!out.is_open()) {
        if (error_msg) *error_msg = "Failed to write hostapd config to " + config_path_;
        return false;
    }
    out << generate_config_string(config);
    out.close();

    if (!command_exists("hostapd")) {
        // hostapd binary is not installed on system
        if (error_msg) *error_msg = "hostapd is not installed on this system. Install hostapd to run live Access Points.";
        return false;
    }

    // Kill any existing hostapd
    int existing_pid = read_pid(pid_file_);
    if (existing_pid > 0 && kill(existing_pid, 0) == 0) {
        kill(existing_pid, SIGTERM);
        usleep(50000);
    }

    std::string cmd = "hostapd -B -P " + pid_file_ + " " + config_path_;
    int res = std::system(cmd.c_str());
    if (res != 0) {
        if (error_msg) *error_msg = "hostapd exited with error status " + std::to_string(res);
        return false;
    }

    pid_ = read_pid(pid_file_);
    return true;
}

bool HostapdManager::stop(std::string* /*error_msg*/) {
    int pid = (pid_ > 0) ? pid_ : read_pid(pid_file_);
    if (pid > 0 && kill(pid, 0) == 0) {
        kill(pid, SIGTERM);
        usleep(50000);
        if (kill(pid, 0) == 0) {
            kill(pid, SIGKILL);
        }
    }

    pid_ = -1;
    std::error_code ec;
    fs::remove(pid_file_, ec);
    return true;
}

bool HostapdManager::is_running() const {
    int pid = (pid_ > 0) ? pid_ : read_pid(pid_file_);
    return pid > 0 && kill(pid, 0) == 0;
}

std::vector<std::string> HostapdManager::get_associated_stations() const {
    std::vector<std::string> stations;
    if (!is_running() || !command_exists("hostapd_cli")) {
        return stations;
    }

    std::string out = run_cmd_output("hostapd_cli all_sta 2>/dev/null");
    std::istringstream iss(out);
    std::string line;
    while (std::getline(iss, line)) {
        // Look for MAC address lines: format XX:XX:XX:XX:XX:XX
        if (line.size() == 17 && line[2] == ':' && line[5] == ':' && line[8] == ':' && line[11] == ':' && line[14] == ':') {
            stations.push_back(line);
        }
    }
    return stations;
}

} // namespace apm::linux_backend
