#include "network/dhcp.hpp"

#include <cstdlib>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <iostream>
#include <filesystem>
#include <unistd.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>

namespace fs = std::filesystem;

namespace apm::network {

namespace {

int read_pid_from_file(const std::string& pid_file) {
    std::ifstream in(pid_file);
    if (!in.is_open()) return -1;
    int pid = -1;
    in >> pid;
    return pid;
}

} // namespace

DhcpServer::~DhcpServer() {
    stop();
}

bool DhcpServer::start(const DhcpConfig& config, const std::string& lease_file) {
    std::error_code ec;
    fs::create_directories("config/run", ec);

    config_path_ = fs::absolute("config/run/dnsmasq.conf").string();
    std::string pid_file = fs::absolute("config/run/dnsmasq.pid").string();
    std::string abs_lease_file = fs::absolute(lease_file).string();

    // Write dnsmasq.conf
    std::ofstream out(config_path_);
    if (!out.is_open()) {
        return false;
    }

    out << "# dnsmasq configuration generated by AP-Generator\n";
    out << "interface=" << config.interface << "\n";
    out << "bind-interfaces\n";
    out << "listen-address=" << config.gateway_ip << "\n";
    out << "except-interface=lo\n";
    out << "dhcp-range=" << config.range_start << "," << config.range_end << "," << config.netmask << "," << config.lease_time << "\n";
    out << "dhcp-option=option:router," << config.gateway_ip << "\n";
    out << "dhcp-option=option:dns-server," << config.gateway_ip << "\n";
    if (config.enable_captive_portal) {
        // RFC 8908 / RFC 8910 Captive Portal Architecture DHCP option
        out << "dhcp-option=114,http://" << config.gateway_ip << ":" << config.portal_port << "/\n";
        out << "address=/#/" << config.gateway_ip << "\n";
    }
    out << "dhcp-leasefile=" << abs_lease_file << "\n";
    out << "dhcp-authoritative\n";
    out << "no-poll\n";
    out << "no-resolv\n";
    out << "server=8.8.8.8\n";
    out << "server=1.1.1.1\n";
    out.close();

    // Kill any previous instance if running
    int existing_pid = read_pid_from_file(pid_file);
    if (existing_pid > 0 && kill(existing_pid, 0) == 0) {
        kill(existing_pid, SIGTERM);
        usleep(50000);
    }

    // Launch dnsmasq using absolute paths
    std::string cmd = "dnsmasq --conf-file=" + config_path_ + " --pid-file=" + pid_file;
    int res = std::system(cmd.c_str());
    if (res == 0) {
        pid_ = read_pid_from_file(pid_file);
        return true;
    }

    return false;
}

bool DhcpServer::stop() {
    std::string pid_file = fs::absolute("config/run/dnsmasq.pid").string();
    int pid = (pid_ > 0) ? pid_ : read_pid_from_file(pid_file);

    if (pid > 0 && kill(pid, 0) == 0) {
        kill(pid, SIGTERM);
        usleep(50000);
        if (kill(pid, 0) == 0) {
            kill(pid, SIGKILL);
        }
    }

    pid_ = -1;
    std::error_code ec;
    fs::remove(pid_file, ec);
    return true;
}

bool DhcpServer::is_running() const {
    std::string pid_file = fs::absolute("config/run/dnsmasq.pid").string();
    int pid = (pid_ > 0) ? pid_ : read_pid_from_file(pid_file);
    return pid > 0 && kill(pid, 0) == 0;
}

std::vector<DhcpLease> DhcpServer::get_leases(const std::string& lease_file) const {
    std::vector<DhcpLease> leases;
    std::string abs_lease_file = fs::absolute(lease_file).string();
    std::ifstream in(abs_lease_file);
    if (!in.is_open()) {
        return leases;
    }

    std::string line;
    while (std::getline(in, line)) {
        std::istringstream iss(line);
        std::string expiry, mac, ip, hostname, client_id;
        if (iss >> expiry >> mac >> ip >> hostname) {
            DhcpLease lease;
            lease.expiry = expiry;
            lease.mac = mac;
            lease.ip = ip;
            lease.hostname = (hostname == "*") ? "Unknown" : hostname;
            leases.push_back(lease);
        }
    }

    return leases;
}

} // namespace apm::network
