#include "network/dns.hpp"

#include <sstream>

namespace apm::network {

std::string DnsServer::generate_dns_config(const DnsConfig& config) {
    std::ostringstream oss;
    oss << "# DNS Configuration generated by AP-Generator\n";
    oss << "domain-needed\n";
    oss << "bogus-priv\n";
    oss << "no-resolv\n";
    oss << "no-poll\n";

    if (config.captive_portal_dns) {
        // Redirection of all domain lookups to captive portal gateway
        std::string target = config.captive_redirect_ip.empty() ? config.listen_ip : config.captive_redirect_ip;
        oss << "address=/#/" << target << "\n";
    } else {
        for (const auto& upstream : config.upstream_servers) {
            oss << "server=" << upstream << "\n";
        }
    }

    return oss.str();
}

} // namespace apm::network
